# Game Design Document (GDD) Workflow
name: gdd
description: "Game Design Document workflow for all game project levels - from small prototypes to full AAA games. Generates comprehensive GDD with game mechanics, systems, progression, and implementation guidance."
author: "BMad"

# Critical variables from config
config_source: "{project-root}/_bmad/gds/config.yaml"
output_folder: "{config_source}:output_folder"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
document_output_language: "{config_source}:document_output_language"
game_dev_experience: "{config_source}:game_dev_experience"
date: system-generated

# Workflow components - Step-file architecture
installed_path: "{project-root}/_bmad/gds/workflows/2-design/gdd"
instructions: "{installed_path}/workflow.md"
template: "{installed_path}/templates/gdd-template.md"
game_types_csv: "{installed_path}/game-types.csv"

# Output configuration
default_output_file: "{output_folder}/gdd.md"

# Game type references (loaded based on game type selection)
game_type_guides: "{installed_path}/game-types/"

# Smart input file references - handles both whole docs and sharded docs
# Priority: Whole document first, then sharded version
input_file_patterns:
  game_brief:
    description: "Game vision and core concept (optional)"
    whole: "{output_folder}/*game-brief*.md"
    sharded: "{output_folder}/*game-brief*/index.md"
    load_strategy: "INDEX_GUIDED"

  research:
    description: "Market or domain research (optional)"
    whole: "{output_folder}/*research*.md"
    sharded: "{output_folder}/*research*/index.md"
    load_strategy: "FULL_LOAD"

  document_project:
    description: "Brownfield project documentation (optional)"
    sharded: "{output_folder}/index.md"
    load_strategy: "INDEX_GUIDED"

standalone: true

web_bundle:
  name: "gdd"
  description: "Game Design Document workflow for all game project levels - from small prototypes to full AAA games. Generates comprehensive GDD with game mechanics, systems, progression, and implementation guidance."
  author: "BMad"
  instructions: "_bmad/gds/workflows/2-design/gdd/workflow.md"
  web_bundle_files:
    # Main workflow file
    - "_bmad/gds/workflows/2-design/gdd/workflow.md"
    # Step files
    - "_bmad/gds/workflows/2-design/gdd/steps/step-01-init.md"
    - "_bmad/gds/workflows/2-design/gdd/steps/step-01b-continue.md"
    - "_bmad/gds/workflows/2-design/gdd/steps/step-02-context.md"
    - "_bmad/gds/workflows/2-design/gdd/steps/step-03-platforms.md"
    - "_bmad/gds/workflows/2-design/gdd/steps/step-04-vision.md"
    - "_bmad/gds/workflows/2-design/gdd/steps/step-05-core-gameplay.md"
    - "_bmad/gds/workflows/2-design/gdd/steps/step-06-mechanics.md"
    - "_bmad/gds/workflows/2-design/gdd/steps/step-07-game-type.md"
    - "_bmad/gds/workflows/2-design/gdd/steps/step-08-progression.md"
    - "_bmad/gds/workflows/2-design/gdd/steps/step-09-levels.md"
    - "_bmad/gds/workflows/2-design/gdd/steps/step-10-art-audio.md"
    - "_bmad/gds/workflows/2-design/gdd/steps/step-11-technical.md"
    - "_bmad/gds/workflows/2-design/gdd/steps/step-12-epics.md"
    - "_bmad/gds/workflows/2-design/gdd/steps/step-13-metrics.md"
    - "_bmad/gds/workflows/2-design/gdd/steps/step-14-complete.md"
    # Template
    - "_bmad/gds/workflows/2-design/gdd/templates/gdd-template.md"
    # Data files
    - "_bmad/gds/workflows/2-design/gdd/game-types.csv"
    # Game type guides
    - "_bmad/gds/workflows/2-design/gdd/game-types/action-platformer.md"
    - "_bmad/gds/workflows/2-design/gdd/game-types/adventure.md"
    - "_bmad/gds/workflows/2-design/gdd/game-types/card-game.md"
    - "_bmad/gds/workflows/2-design/gdd/game-types/fighting.md"
    - "_bmad/gds/workflows/2-design/gdd/game-types/horror.md"
    - "_bmad/gds/workflows/2-design/gdd/game-types/idle-incremental.md"
    - "_bmad/gds/workflows/2-design/gdd/game-types/metroidvania.md"
    - "_bmad/gds/workflows/2-design/gdd/game-types/moba.md"
    - "_bmad/gds/workflows/2-design/gdd/game-types/party-game.md"
    - "_bmad/gds/workflows/2-design/gdd/game-types/puzzle.md"
    - "_bmad/gds/workflows/2-design/gdd/game-types/racing.md"
    - "_bmad/gds/workflows/2-design/gdd/game-types/rhythm.md"
    - "_bmad/gds/workflows/2-design/gdd/game-types/roguelike.md"
    - "_bmad/gds/workflows/2-design/gdd/game-types/rpg.md"
    - "_bmad/gds/workflows/2-design/gdd/game-types/sandbox.md"
    - "_bmad/gds/workflows/2-design/gdd/game-types/shooter.md"
    - "_bmad/gds/workflows/2-design/gdd/game-types/simulation.md"
    - "_bmad/gds/workflows/2-design/gdd/game-types/sports.md"
    - "_bmad/gds/workflows/2-design/gdd/game-types/strategy.md"
    - "_bmad/gds/workflows/2-design/gdd/game-types/survival.md"
    - "_bmad/gds/workflows/2-design/gdd/game-types/text-based.md"
    - "_bmad/gds/workflows/2-design/gdd/game-types/tower-defense.md"
    - "_bmad/gds/workflows/2-design/gdd/game-types/turn-based-tactics.md"
    - "_bmad/gds/workflows/2-design/gdd/game-types/visual-novel.md"
